// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('app', []).controller('MainCtrl', function($scope, $timeout) {
    var changeBackgroundImage, updateTime;
    $scope.date = {};
    (updateTime = function() {
      $scope.date.tz = new Date;
      return $timeout(updateTime, 1000);
    })();
    return (changeBackgroundImage = function() {
      $scope.backgroundImage = "./img/" + Math.floor(1 + Math.random() * 8) + ".jpg";
      document.getElementsByTagName("html")[0].style.backgroundImage = $scope.backgroundImage;
      return $timeout(changeBackgroundImage, 30000);
    })();
  });

}).call(this);
